# Generated by Django 4.2.6 on 2023-10-25 21:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('proyecto_trabajo_final', '0001_initial'),
        ('dictamenes', '0001_initial'),
        ('comisiones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluacionptf_te',
            name='ptf_evaluadoTE',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='proyecto_trabajo_final.proyectofinal'),
        ),
        migrations.AddField(
            model_name='evaluacionptf_cstf',
            name='evaluadorCSTF',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comisiones.comision'),
        ),
        migrations.AddField(
            model_name='evaluacionptf_cstf',
            name='ptf_evaluadoCSTF',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='proyecto_trabajo_final.proyectofinal'),
        ),
        migrations.AddField(
            model_name='evaluacionitf',
            name='evaluadorTE_ITF',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='comisiones.tribunalevaluador'),
        ),
        migrations.AddField(
            model_name='evaluacionitf',
            name='itf_evaluadoTE',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='proyecto_trabajo_final.informetf'),
        ),
    ]
