# Generated by Django 4.2.6 on 2023-10-19 21:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('persona', '0002_alter_asesor_curriculum'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProyectoFinal',
            fields=[
                ('id', models.CharField(max_length=8, primary_key=True, serialize=False, unique=True)),
                ('titulo', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=250)),
                ('fechaPresentacion', models.DateField()),
                ('proyectoFinal', models.FileField(upload_to='')),
                ('notaAceptacionDirector', models.FileField(upload_to='')),
                ('fechaAltaDirector', models.DateField()),
                ('fechaBajaDirector', models.DateField(blank=True, null=True)),
                ('asesor', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proyectos_asesor', to='persona.docente')),
                ('coDirector', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proyectos_co_director', to='persona.docente')),
                ('director', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proyectos_director', to='persona.docente')),
            ],
        ),
        migrations.CreateModel(
            name='PTF_Integrantes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaAltaAlumno', models.DateField(blank=True, null=True)),
                ('fechaBajaAlumno', models.DateField(blank=True, null=True)),
                ('certificadoAnalitico', models.FileField(upload_to='')),
                ('alumnos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='persona.alumno')),
                ('proyectoFinal', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='proyecto_trabajo_final.proyectofinal')),
            ],
        ),
        migrations.CreateModel(
            name='Movimientos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(max_length=50)),
                ('fechaMovimiento', models.DateField()),
                ('archivoAsociado', models.FileField(blank=True, null=True, upload_to='')),
                ('tipoMovimiento', models.CharField(max_length=50)),
                ('fechaVencimiento', models.DateField(blank=True, null=True)),
                ('fechaCulminacion', models.DateField(blank=True, null=True)),
                ('proyectoFinal', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='proyecto_trabajo_final.proyectofinal')),
            ],
        ),
    ]
