# Generated by Django 4.2.6 on 2023-10-25 21:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('persona', '0002_alter_asesor_curriculum'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProyectoFinal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=250)),
                ('fechaPresentacion', models.DateField()),
                ('proyectoFinal', models.FileField(upload_to='archivosPTF/')),
            ],
        ),
        migrations.CreateModel(
            name='TutoresPTF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaAltaTutor', models.DateField()),
                ('fechaBajaTutor', models.DateField(blank=True, null=True)),
                ('notaAceptacion', models.FileField(blank=True, null=True, upload_to='archivosPTF/')),
                ('rol_tutor', models.CharField(choices=[('codirector', 'Codirector'), ('director', 'Director')], max_length=50)),
                ('docente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proyectos_tutores', to='persona.docente')),
            ],
        ),
        migrations.CreateModel(
            name='PTF_Integrantes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaAltaAlumno', models.DateField(blank=True, null=True)),
                ('fechaBajaAlumno', models.DateField(blank=True, null=True)),
                ('certificadoAnalitico', models.FileField(upload_to='archivosPTF/')),
                ('alumnos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proyectos', to='persona.alumno')),
                ('proyectoFinal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='proyecto_trabajo_final.proyectofinal')),
            ],
        ),
        migrations.CreateModel(
            name='Movimientos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('aceptado', 'Aceptado'), ('rechazado', 'Rechazado'), ('observado', 'Observado')], max_length=50)),
                ('tipoMovimiento', models.CharField(choices=[('presentacion ptf', 'Presentación PTF'), ('pase a la cstf', 'Pase a la CSTF'), ('dictamen de la cstf sobre el formato del ptf', 'Dictamen de la CSTF sobre el formato del PTF'), ('pase al te', 'Pase al TE'), ('dictamen tribunal evaluador sobre evaluación ptf', 'Dictamen tribunal evaluador sobre evaluación PTF'), ('presentación borrador informe final', 'Presentación borrador Informe final'), ('dictamen tribunal evaluador sobre borrador', 'dictamen tribunal evaluador sobre borrador')], max_length=50)),
                ('observacion', models.CharField(blank=True, max_length=50, null=True)),
                ('fechaMovimiento', models.DateField()),
                ('archivoAsociado', models.FileField(blank=True, null=True, upload_to='archivosPTF/')),
                ('fechaVencimiento', models.DateField(blank=True, null=True)),
                ('proyectoFinal', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='proyecto_trabajo_final.proyectofinal')),
            ],
        ),
        migrations.CreateModel(
            name='InformeTF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivoITF', models.FileField(upload_to='archivosPTF/')),
                ('fechaPresentacion', models.DateField()),
                ('proyectoTF', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='proyecto_trabajo_final.proyectofinal')),
            ],
        ),
        migrations.CreateModel(
            name='AsesorPTF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaAltaAsesor', models.DateField()),
                ('fechaBajaAsesor', models.DateField(blank=True, null=True)),
                ('notaAceptacion', models.FileField(blank=True, null=True, upload_to='archivosPTF/')),
                ('asesor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proyectos_asesor', to='persona.asesor')),
            ],
        ),
    ]
