# Generated by Django 4.2.6 on 2023-10-28 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto_trabajo_final', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movimientos',
            old_name='proyectoFinal',
            new_name='proyecto',
        ),
    ]
