# Generated by Django 4.2.6 on 2023-10-28 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto_trabajo_final', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='asesorptf',
            name='proyecto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='proyecto_trabajo_final.proyectofinal'),
        ),
        migrations.AddField(
            model_name='tutoresptf',
            name='proyecto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='proyecto_trabajo_final.proyectofinal'),
        ),
    ]
