# Generated by Django 4.2.6 on 2023-10-20 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto_trabajo_final', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimientos',
            name='observacion',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='movimientos',
            name='estado',
            field=models.CharField(choices=[('aceptado', 'Aceptado'), ('rechazado', 'Rechazado'), ('observado', 'Observado')], max_length=50),
        ),
        migrations.AlterField(
            model_name='movimientos',
            name='tipoMovimiento',
            field=models.CharField(choices=[('presentacion ptf', 'Presentación PTF'), ('pase a la cstf', 'Pase a la CSTF'), ('dictamen de la cstf sobre el formato del ptf', 'Dictamen de la CSTF sobre el formato del PTF'), ('pase al te', 'Pase al TE'), ('dictamen tribunal evaluador sobre evaluación ptf', 'Dictamen tribunal evaluador sobre evaluación PTF'), ('presentación borrador informe final', 'Presentación borrador Informe final'), ('dictamen tribunal evaluador sobre borrador', 'dictamen tribunal evaluador sobre borrador')], max_length=50),
        ),
    ]
