# Generated by Django 4.2.6 on 2023-10-31 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alumno',
            options={'permissions': [('permiso_alumno', 'Permiso alumno')]},
        ),
    ]
