# Generated by Django 4.2.6 on 2023-10-25 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asesor',
            name='curriculum',
            field=models.FileField(upload_to='persona/'),
        ),
    ]
