# Generated by Django 4.2.6 on 2023-10-31 23:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0002_alter_alumno_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='docente',
            options={'permissions': [('permiso_cstf', 'Permiso CSTF'), ('permiso_te', 'Permiso TE')]},
        ),
    ]
