# Generated by Django 4.2.6 on 2023-10-11 20:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('persona', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComisionDeSeguimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaDeCreacion', models.DateField()),
                ('nroResolucion', models.CharField(max_length=30, unique=True)),
                ('docentes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='persona.docente')),
            ],
            options={
                'ordering': ['fechaDeCreacion'],
            },
        ),
    ]
