# Generated by Django 4.2.6 on 2023-10-25 21:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('proyecto_trabajo_final', '0001_initial'),
        ('persona', '0002_alter_asesor_curriculum'),
        ('comisiones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tribunalevaluador',
            name='proyectoTE',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='proyecto_trabajo_final.proyectofinal'),
        ),
        migrations.AddField(
            model_name='integrantestribunal',
            name='docente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='persona.docente'),
        ),
        migrations.AddField(
            model_name='integrantestribunal',
            name='tribunal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comisiones.tribunalevaluador'),
        ),
        migrations.AddField(
            model_name='integrantescomision',
            name='comision',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comisiones.comision'),
        ),
        migrations.AddField(
            model_name='integrantescomision',
            name='docente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='persona.docente'),
        ),
    ]
