# Generated by Django 4.2.6 on 2023-10-11 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0001_initial'),
        ('comisiones', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comisiondeseguimiento',
            options={'ordering': ['fechaDeCreacionComision']},
        ),
        migrations.RenameField(
            model_name='comisiondeseguimiento',
            old_name='docentes',
            new_name='docentesComision',
        ),
        migrations.RenameField(
            model_name='comisiondeseguimiento',
            old_name='fechaDeCreacion',
            new_name='fechaDeCreacionComision',
        ),
        migrations.RenameField(
            model_name='comisiondeseguimiento',
            old_name='nroResolucion',
            new_name='nroResolucionComision',
        ),
        migrations.CreateModel(
            name='TribunalEvaluador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nroResolucionTribunal', models.CharField(max_length=50, unique=True)),
                ('fechaCreacionTribunal', models.DateField()),
                ('rol', models.CharField(choices=[('presidente', 'Presidente'), ('vocal_titular', 'Vocal Titular'), ('vocal_secundario', 'Vocal Secundario')], max_length=16)),
                ('docentesTribunal', models.ManyToManyField(to='persona.docente')),
            ],
            options={
                'ordering': ['fechaCreacionTribunal'],
            },
        ),
    ]
