# Generated by Django 4.2.6 on 2023-10-18 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comisiones', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TribunalEvaluador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nroDisposicionTribunal', models.CharField(max_length=50, unique=True)),
                ('fechaCreacionTribunal', models.DateField()),
                ('archivoDisposicion', models.FileField(upload_to='')),
            ],
            options={
                'ordering': ['fechaCreacionTribunal'],
            },
        ),
    ]
