# Generated by Django 4.2.6 on 2023-10-11 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comisiones', '0002_alter_comisiondeseguimiento_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tribunalevaluador',
            old_name='nroResolucionTribunal',
            new_name='nroDisposicionTribunal',
        ),
    ]
