# Generated by Django 4.2.6 on 2023-10-18 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0002_alter_asesor_curriculum'),
        ('comisiones', '0002_tribunalevaluador'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntegrantesComision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_alta_cs', models.DateField()),
                ('fecha_baja_cs', models.DateField()),
                ('comision', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='comisiones.comision')),
                ('docente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='persona.docente')),
            ],
            options={
                'ordering': ['fecha_alta_cs'],
            },
        ),
    ]
